### ISSUE TITLE
Skipping invalid or unsupported rule

### ISSUE THREAD

**Issue by 3muu** [initstring/passphrase-wordlist#3]
Hello,
if i run the Script i get many error for unsupport rule..

can you Help me?

C:\hashcat>hashcat -a 0 -m 1000 hashes.txt passphrases.txt -r passphrase-rule1.rule -r passphrase-rule2.rule -O -w 3
hashcat (v6.2.5) starting

Unsupported AMD HIP runtime version '0.0.3188' detected! Falling back to OpenCL...

OpenCL API (OpenCL 2.1 AMD-APP (3188.4)) - Platform #1 [Advanced Micro Devices, Inc.]
=====================================================================================
* Device #1: AMD Radeon RX 6900 XT, 8064/8192 MB (6745 MB allocatable), 32MCU
* Device #2: Radeon (TM) RX 470 Graphics, 8064/8192 MB (6745 MB allocatable), 32MCU
* Device #3: AMD Radeon RX 6900 XT, 16256/16368 MB (13695 MB allocatable), 40MCU

OpenCL API (OpenCL 3.0 WINDOWS) - Platform #2 [Intel(R) Corporation]
====================================================================
* Device #4: AMD Ryzen 5 1600 Six-Core Processor, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 27

Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 7: <!DOCTYPE html>
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 8: <html lang="en" data-color-mode="auto" data-light-theme="light" data-dark-theme="dark">
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 9:   <head>
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 10:     <meta charset="utf-8">
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 11:   <link rel="dns-prefetch" href="https://github.githubassets.com">
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 12:   <link rel="dns-prefetch" href="https://avatars.githubusercontent.com">
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 13:   <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 14:   <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 15:   <link rel="preconnect" href="https://github.githubassets.com" crossorigin>
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 16:   <link rel="preconnect" href="https://avatars.githubusercontent.com">
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 20:   <link crossorigin="anonymous" media="all" integrity="sha512-1G4rYJktwRTQKn7fVfJUxH8RRZFUJlGo77xMZfBfIhZPx4BHVrzPE1VgnafttXI8G3y/PywH3uXyhNkSLp3+oA==" rel="stylesheet" href="https://github.githubassets.com/assets/light-d46e2b60992dc114d02a7edf55f254c4.css" /><link crossorigin="anonymous" media="all" integrity="sha512-hI5b2oqTE9njfjYrfuzXqA4bSGSNrE5OMc9IiFhZy+RDGg9Qn4Si1A97o0MlinlwFt3xAifvoLX0s7jHmHSvVw==" rel="stylesheet" href="https://github.githubassets.com/assets/dark-848e5bda8a9313d9e37e362b7eecd7a8.css" /><link data-color-theme="dark_dimmed" crossorigin="anonymous" media="all" integrity="sha512-klQdb3t14AYaRMkB0v9buaf5Ftfbec/sbxdkvyQpG6oBvzZxxH6N5QwA4llOyZsoyjqiZaTra2ci5TgInnLqQg==" rel="stylesheet" data-href="https://github.githubassets.com/assets/dark_dimmed-92541d6f7b75e0061a44c901d2ff5bb9.css" /><link data-color-theme="dark_high_contrast" crossorigin="anonymous" media="all" integrity="sha512-CBsfpBvg1D/Hvn8FFY4JwUVgoKjgynOSFKwgThDHrHASVid/Isgz0ueab5xSuSVx8vEvNL9UfYcpWIJRJYTCjg==" rel="stylesheet" data-href="https://github.githubassets.com/assets/dark_high_contrast-081b1fa41be0d43fc7be7f05158e09c1.css" /><link data-color-theme="dark_colorblind" crossorigin="anonymous" media="all" integrity="sha512-09ipkynAtzCqasl2D2//N51bUOVnOzBFdadcXdMWyphI81s1FWmJ9AD1NRq3e0PMfiJEiVSm9mjTYd7gv2xtWA==" rel="stylesheet" data-href="https://github.githubassets.com/assets/dark_colorblind-d3d8a99329c0b730aa6ac9760f6fff37.css" /><link data-color-theme="light_colorblind" crossorigin="anonymous" media="all" integrity="sha512-OJwnC/pGdOV3QMoWud8vp0nxtQhtzAcpNWB7mSSh/e7fPslExSb07EOdNTAJsBAS4bN7Yrdxm2F7htANgTIMsA==" rel="stylesheet" data-href="https://github.githubassets.com/assets/light_colorblind-389c270bfa4674e57740ca16b9df2fa7.css" /><link data-color-theme="light_high_contrast" crossorigin="anonymous" media="all" integrity="sha512-5swg0RJGlhj0UH3SLkJ6e/BYm/DmpyGTaUSCUBhf1HtC4lBV+zM9mxOQ8febH318pxcUzUpp09qi0z7EKfWuDQ==" rel="stylesheet" data-href="https://github.githubassets.com/assets/light_high_contrast-e6cc20d112469618f4507dd22e427a7b.css" />
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 21:   <link crossorigin="anonymous" media="all" integrity="sha512-T3N453hWCYsL8yKfu3yye2yyO/D51Lq2iT5svAdl7UKvV2rBPcV7iOgr3fihzB9vYV7YFIK3PxpyTTkfxAshog==" rel="stylesheet" href="https://github.githubassets.com/assets/frameworks-4f7378e77856098b0bf3229fbb7cb27b.css" />
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 22:   <link crossorigin="anonymous" media="all" integrity="sha512-07Fhxaln6iqVJ4z2DB1ClmjJlWF7DzfsNoKUsyssjWIHwaRn5kHhGuiMih3gqL6MvY9nu7mIRMSzIoxpAb9dlg==" rel="stylesheet" href="https://github.githubassets.com/assets/behaviors-d3b161c5a967ea2a95278cf60c1d4296.css" />
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 23:   <link crossorigin="anonymous" media="all" integrity="sha512-MCJFYfbQoT4EXC6aWx5Wghs8FC/jslHEeN2iWXphliccmede2dQlhIBTAUCBq9Yu5poltu4askungzvyCsycGg==" rel="stylesheet" href="https://github.githubassets.com/assets/tab-size-fix-30224561f6d0a13e045c2e9a5b1e5682.css" />
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 27:   <link crossorigin="anonymous" media="all" integrity="sha512-s6gQ9zPmpX9HnhI35eVCp8zhuTUUEsP2bEbw5wm8DqB0eGsiHVfGDC+mIBp9RvV3pQLa2Gmu5GRqKVzIjb5lDg==" rel="stylesheet" href="https://github.githubassets.com/assets/github-b3a810f733e6a57f479e1237e5e542a7.css" />
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 29:   <script crossorigin="anonymous" defer="defer" integrity="sha512-K/kjAAGVhlckApEbskyYOB+ASq3m0GKyJk3y0JoEafwknEbUpmilodEuQQJG09c0v1eCRlX7mSQp+GLGtXmWQg==" type="application/javascript" src="https://github.githubassets.com/assets/environment-2bf92300.js"></script>
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 30:     <script crossorigin="anonymous" defer="defer" integrity="sha512-43iG02uHDU3x1xWQNOFjY5BxmQ+LTKcrSjWdiPtpjTMSrAK3WPEHC62jVFyRTq7jjdbZF3Vn265iEWYBCd5GIQ==" type="application/javascript" src="https://github.githubassets.com/assets/chunk-frameworks-e37886d3.js"></script>
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 31:     <script crossorigin="anonymous" defer="defer" integrity="sha512-pEuiC5g/bPxJ6DWhOK4vgGNJ82p1B9O9OrUM4c8qCrzkZqAsDILOk8S3wr7ToHsGAa0UOyM7Y4dscERce7tARQ==" type="application/javascript" src="https://github.githubassets.com/assets/chunk-vendor-a44ba20b.js"></script>
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 33:   <script crossorigin="anonymous" defer="defer" integrity="sha512-M3/Rihza1N1EAYmwRjrDWMWE2/pK+XEKJIgaCYtWV0kQXABGP3X2QLVlkXWzA313a8TxZxyGDRXPdCd2R/VTyQ==" type="application/javascript" src="https://github.githubassets.com/assets/behaviors-337fd18a.js"></script>
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 35:     <script crossorigin="anonymous" defer="defer" integrity="sha512-ODZJzCJpaOfusrIka5QVZQcPiO9LBGyrrMYjhhJWSLuCN5WbZ5xiEiiOPOKVu71dqygyRdB2TY7AKPA1J5hqdg==" type="application/javascript" data-module-id="./chunk-unveil.js" data-src="https://github.githubassets.com/assets/chunk-unveil-383649cc.js"></script>
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 36:     <script crossorigin="anonymous" defer="defer" integrity="sha512-emPgUbSwW9ezLCgRnTE7n4fbbfc/MqEEDHmnkmG61dTyjWKHTYKN4wN3OPS7SY0fwmSJ8mB5+gng2nZw4/HsUg==" type="application/javascript" data-module-id="./chunk-animate-on-scroll.js" data-src="https://github.githubassets.com/assets/chunk-animate-on-scroll-7a63e051.js"></script>
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 37:     <script crossorigin="anonymous" defer="defer" integrity="sha512-x6L94lNXrnj4GyXhVug6j63GettxBVe/yQmgJU42IbfJet6sW2RBDG4tbZVkLbOCiYrNy+1Zwvoc1gA6uzSPow==" type="application/javascript" data-module-id="./chunk-input-demux.js" data-src="https://github.githubassets.com/assets/chunk-input-demux-c7a2fde2.js"></script>
Skipping invalid or unsupported rule in file passphrase-rule1.rule on line 38:     <script crossorigin="anonymous" defer="defer" integrity="sha512-d9zLk770daEV3pV4uNV22h2h49h/QxYstihxVyOEMetKZVhZcWW9bbqXOp2e1I7sIpuIj3xcpUSdlZKJxdl3tw==" type="application/javascript" data-module-id="./chunk-ref-selector.js" data-src="https://github.githubassets.com/assets/chunk-ref-selector-77dccb93.js"></script>

**Comment by initstring** [comment]
Hello,

It looks like you might have accidentally downloaded website source code instead of the rule file. The errors you post above are showing some Javascript code that looks to be hosted by github.com, not the actual content of the rule file.

If you look closely, passphrase-rule1.rule is only 16 lines long. However, your errors above are showing many more lines and are reflecting content that does not exist in the actual rule file.

There are a few easy ways you can get the raw files. In the repository root, you can click "Code -> Download Zip". Or you can go to each rule file linked in the README and then click the "raw" button to make sure you are accessing the actual file and not just the webpage GitHub is hosting it on.

Good luck!
