### ISSUE TITLE
rules being skipped

### ISSUE THREAD

**Issue by eliddell1** [initstring/passphrase-wordlist#4]
First let me thank you for this innovative approach to pass phrases and rules.  I am running hashcat 6.2.6 on windows.  (I know, windows, but thats the machine with my Nvidia 3070 Cards)

anyway, hashcat does not like most of the rules.  the log is too large to paste, but I am getting this error over and over again

```
Skipping invalid or unsupported rule in file rules\passphrase-rule2.rule on line 531: </li>
Skipping invalid or unsupported rule in file rules\passphrase-rule2.rule on line 533:             </ul>
Skipping invalid or unsupported rule in file rules\passphrase-rule2.rule on line 534:           </nav>
Skipping invalid or unsupported rule in file rules\passphrase-rule2.rule on line 536:         <div class="d-lg-flex flex-items-center px-3 px-lg-0 mb-3 mb-lg-0 text-center text-lg-left">
Skipping invalid or unsupported rule in file rules\passphrase-rule2.rule on line 537:             <div class="d-lg-flex min-width-0 mb-2 mb-lg-0">
Skipping invalid or unsupported rule in file rules\passphrase-rule2.rule on line 542: <div class="header-search flex-auto position-relative js-site-search flex-self-stretch flex-md-self-auto mb-3 mb-md-0 mr-0 mr-md-3 scoped-search site-scoped-search js-jump-to"
```

get this type of error on both rules running a command like this:
`hashcat.exe -m 22000  spncdump.hc22000 wordlists\passphrases.txt -S -r rules\passphrase-rule2.rule`

**Comment by eliddell1** [comment]
downloaded the raw version and it worked.. was an html  file otherwise

**Comment by initstring** [comment]
Hi @eliddell1 ,

No worries, this can happen easily and you are not the first to do this. :)

I wish you success in all your cracking endeavours. Have a good day. :)
